version: '3.9'
services:
    nginx_proxy:
        build:
            context: .
            dockerfile: devops/dockerfiles/proxy/Nginx.Dockerfile
        container_name: nginx_proxy
        #    volumes:
        #      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        volumes:
            - ./conf/nginx:/src
        ports:
            - "80:80"
        depends_on:
            # - symfony_backend
            # - django_backend
            # - springboot_backend
            # - front_micro
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
