version: '3.9'
services:
    front_test:
        build:
            context: .
            dockerfile: devops/Dockerfile
        container_name: front_test
        ports:
            - "5180:5173"
        entrypoint: [ "/app/entrypoint.sh" ]
        volumes:
            - ./project:/app
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
