framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.native_php_serializer
        transports:
            events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                retry_strategy:
                    max_retries: 3
                    delay: 1000  # Tiempo en milisegundos entre intentos
                    multiplier: 2
                    max_delay: 10000  # Tiempo máximo de espera entre intentos
        routing:
            'App\Shared\Domain\Bus\Event\DomainEvent': events
