doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGO_DB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGO_DB_NAME)%'
    document_managers:
        default:
            auto_mapping: true
#            default_document_repository_class: 'App\Main\Infrastructure\Repositories\Mongo\PokemonBaseRepository'
            mappings:
                Mongo:
                    is_bundle: false
#                    type: xml
                    dir: '%kernel.project_dir%/src/Main/Domain/Model/Mongo'
                    prefix: 'App\Main\Domain\Model\Mongo'
                    alias: Mongo
